function q_i = p_forward_kinematics(a_i, b_b, ln, q_0, r_p)
    q_i = q_0;
    J = Jacobian(a_i, b_b, q_i, ln, r_p);
    A = J.'*J;
    phi = nusq(a_i, b_b, q_i, ln, r_p);
    
    g = J.'*phi;
    
    % MarLev position estimation constants
    tau       = 1e-6;
    epsilon_1 = 1e-17;
    epsilon_2 = 1e-17;
    xi        = 2;
    mu        = tau*max(diag(A));
    
    iter = 0;
    max_iter = 100;
    
    stop = false;
    while ~stop && iter < max_iter
        iter = iter+1;
    
        h = (A + mu*eye(3))\(-g);
        
        if norm(h,2) <= epsilon_2*(norm(q_i,2)+epsilon_2)
            disp('Cond 1')
            stop = true;
        else
            q_new = q_i + h;
    
            % Gain ratio
            Phi = 0.5*(phi.')*phi; % phi = nu^2(q)
            phi_x_plus_h = nusq(a_i, b_b, q_new, ln, r_p);
            
            Phi_x_plus_h = 0.5*(phi_x_plus_h.')*phi_x_plus_h;
            rho = (Phi - Phi_x_plus_h)/(0.5*(h.')*(mu*h - g));
    
            if rho > 0
                q_i = q_new;
                J = Jacobian(a_i, b_b, q_i, ln, r_p);
                A = J.'*J;
                phi = nusq(a_i, b_b, q_i, ln, r_p);
                g = J.'*phi;
                cond = norm(g,2) < epsilon_1;
                if cond
                    disp('Cond2')
                    stop = cond;
                end
                mu = mu*max([1/3, 1-(2*rho-1)^3]);
                xi = 2;
            else
                mu = mu*xi;
                xi = 2*xi;
            end
        end
    end
    iter
end

function J = Jacobian(a, b, pose, l, r_p)
    x = pose(1);
    y = pose(2);
    theta = pose(3);
    
    c = cos(theta);
    s = sin(theta);

    a1x = a(1,1);
    a1y = a(2,1);
    a2x = a(1,2);
    a2y = a(2,2);
    a3x = a(1,3);
    a3y = a(2,3);
    a4x = a(1,4);
    a4y = a(2,4);

    b1x = b(1,1);
    b1y = b(2,1);
    b2x = b(1,2);
    b2y = b(2,2);
    b3x = b(1,3);
    b3y = b(2,3);
    b4x = b(1,4);
    b4y = b(2,4);

    l1 = l(1);
    l2 = l(2);
    l3 = l(3);
    l4 = l(4);

%     J1_x     = -2*(                                               ...
%                     r_p*(2*a1x - 2*x - 2*b1x*c + 2*b1y*s) +       ...
%                     (a1x - x - b1x*c + b1y*s)^2 +                 ...
%                     (y - a1y + b1y*c + b1x*s)^2 - l1^2            ...
%                   )*                                              ...
%                   (                                               ...
%                     2*a1x + 2*r_p - 2*x - 2*b1x*c + 2*b1y*s       ...
%                   );
%     J1_y     =  2*(                                               ...
%                     r_p*(2*a1x - 2*x - 2*b1x*c + 2*b1y*s) +       ...
%                     (a1x - x - b1x*c + b1y*s)^2 +                 ...
%                     (y - a1y + b1y*c + b1x*s)^2 -                 ...
%                     l1^2                                          ...
%                   )*                                              ...
%                   (                                               ...
%                     2*y - 2*a1y + 2*b1y*c + 2*b1x*s               ...
%                   );
%     J1_theta =  2*(                                               ...
%                     r_p*(2*b1y*c + 2*b1x*s) +                     ...
%                     2*(b1y*c + b1x*s)*(a1x - x - b1x*c + b1y*s) + ...
%                     2*(b1x*c - b1y*s)*(y - a1y + b1y*c + b1x*s)   ...
%                   ) *                                             ...
%                   (                                               ...
%                     r_p*(2*a1x - 2*x - 2*b1x*c + 2*b1y*s) +       ...
%                     (a1x - x - b1x*c + b1y*s)^2 +                 ...
%                     (y - a1y + b1y*c + b1x*s)^2 -                 ...
%                     l1^2                                          ...
%                   );
%     
%     J2_x     = -2*(                                               ...
%                     r_p*(2*a2x - 2*x - 2*b2x*c + 2*b2y*s) +       ...
%                     (a2x - x - b2x*c + b2y*s)^2 +                 ...
%                     (y - a2y + b2y*c + b2x*s)^2 -                 ...
%                     l2^2                                          ...
%                   )*                                              ...
%                   (                                               ...
%                     2*a2x + 2*r_p - 2*x - 2*b2x*c + 2*b2y*s       ...
%                   );
%     J2_y     =  2*(                                               ...
%                     r_p*(2*a2x - 2*x - 2*b2x*c + 2*b2y*s) +       ...
%                     (a2x - x - b2x*c + b2y*s)^2 +                 ...
%                     (y - a2y + b2y*c + b2x*s)^2 -                 ...
%                     l2^2                                          ...
%                   )*                                              ...
%                   (2*y - 2*a2y + 2*b2y*c + 2*b2x*s);
%     J2_theta =  2*(                                               ...
%                     r_p*(2*b2y*c + 2*b2x*s) +                     ...
%                     2*(b2y*c + b2x*s)*(a2x - x - b2x*c + b2y*s) + ...
%                     2*(b2x*c - b2y*s)*(y - a2y + b2y*c + b2x*s)   ...
%                   )*                                              ...
%                   (                                               ...
%                     r_p*(2*a2x - 2*x - 2*b2x*c + 2*b2y*s) +       ...
%                     (a2x - x - b2x*c + b2y*s)^2 +                 ...
%                     (y - a2y + b2y*c + b2x*s)^2 -                 ...
%                     l2^2                                          ...
%                   );
% 
%     J3_x     = -2*(                                               ...
%                     r_p*(2*a3x - 2*x - 2*b3x*c + 2*b3y*s) -       ...
%                     (a3x - x - b3x*c + b3y*s)^2 -                 ...
%                     (y - a3y + b3y*c + b3x*s)^2 + l3^2            ...
%                   )*                                              ...
%                   (2*r_p - 2*a3x + 2*x + 2*b3x*c - 2*b3y*s);
%     J3_y     = -2*(2*y - 2*a3y + 2*b3y*c + 2*b3x*s)*              ...
%                   (                                               ...
%                     r_p*(2*a3x - 2*x - 2*b3x*c + 2*b3y*s) -       ...
%                     (a3x - x - b3x*c + b3y*s)^2 -                 ...
%                     (y - a3y + b3y*c + b3x*s)^2 +                 ...
%                     l3^2                                          ...
%                   );
%     J3_theta = -2*(                                               ...
%                     2*(b3y*c + b3x*s)*(a3x - x - b3x*c + b3y*s) - ...
%                     r_p*(2*b3y*c + 2*b3x*s) +                     ...
%                     2*(b3x*c - b3y*s)*(y - a3y + b3y*c + b3x*s)   ...
%                   )*                                              ...
%                   (                                               ...
%                     r_p*(2*a3x - 2*x - 2*b3x*c + 2*b3y*s) -       ...
%                     (a3x - x - b3x*c + b3y*s)^2 -                 ...
%                     (y - a3y + b3y*c + b3x*s)^2 +                 ...
%                     l3^2                                          ...
%                   );
% 
%     J4_x     = -2*(                                               ...
%                     r_p*(2*a4x - 2*x - 2*b4x*c + 2*b4y*s) -       ...
%                     (a4x - x - b4x*c + b4y*s)^2 -                 ...
%                     (y - a4y + b4y*c + b4x*s)^2 + l4^2            ...
%                   )*                                              ...
%                   (2*r_p - 2*a4x + 2*x + 2*b4x*c - 2*b4y*s);
%     J4_y     = -2*(2*y - 2*a4y + 2*b4y*c + 2*b4x*s)*              ...
%                   (                                               ...
%                     r_p*(2*a4x - 2*x - 2*b4x*c + 2*b4y*s) -       ...
%                     (a4x - x - b4x*c + b4y*s)^2 -                 ...
%                     (y - a4y + b4y*c + b4x*s)^2 +                 ...
%                     l4^2                                          ...
%                   );
%     J4_theta = -2*(                                               ...
%                     2*(b4y*c + b4x*s)*(a4x - x - b4x*c + b4y*s) - ...
%                     r_p*(2*b4y*c + 2*b4x*s) +                     ...
%                     2*(b4x*c - b4y*s)*(y - a4y + b4y*c + b4x*s)   ...
%                   )*                                              ...
%                   (                                               ...
%                     r_p*(2*a4x - 2*x - 2*b4x*c + 2*b4y*s) -       ...
%                     (a4x - x - b4x*c + b4y*s)^2 -                 ...
%                     (y - a4y + b4y*c + b4x*s)^2 +                 ...
%                     l4^2                                          ...
%                   );

    J1_x = -4*(r_p*(((y - a1y + b1y*cos(theta) + b1x*sin(theta))*(2*a1x + 2*r_p - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta)))/(2*((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2)^(3/2)*(1 - (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2/((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2))^(1/2)) + (r_p^2*(a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta)))/((1 - (r_p*(2*a1x - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta)) + (a1x - x - b1x*cos(theta) + b1y*sin(theta))^2 + (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2)/((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2))^(1/2)*((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2)^(3/2)*(r_p*(2*a1x - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta)) + (a1x - x - b1x*cos(theta) + b1y*sin(theta))^2 + (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2)^(1/2))) - (2*a1x + 2*r_p - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta))/(2*(r_p*(2*a1x - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta)) + (a1x - x - b1x*cos(theta) + b1y*sin(theta))^2 + (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2)^(1/2)))*((r_p*(2*a1x - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta)) + (a1x - x - b1x*cos(theta) + b1y*sin(theta))^2 + (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2)^(1/2) + r_p*(pi - acos((y - a1y + b1y*cos(theta) + b1x*sin(theta))/((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2)^(1/2)) + acos((r_p*(2*a1x - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta)) + (a1x - x - b1x*cos(theta) + b1y*sin(theta))^2 + (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2)^(1/2)/((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2)^(1/2)) - 2237/12500))*(l1^2 - (12500*pi*r_p - 12500*r_p*acos((y - a1y + b1y*cos(theta) + b1x*sin(theta))/((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2)^(1/2)) - 2237*r_p + 12500*(r_p*(2*a1x - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta)) + (a1x - x - b1x*cos(theta) + b1y*sin(theta))^2 + (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2)^(1/2) + 12500*r_p*acos((r_p*(2*a1x - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta)) + (a1x - x - b1x*cos(theta) + b1y*sin(theta))^2 + (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2)^(1/2)/((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2)^(1/2)))^2/156250000);
    J1_y = -4*((r_p*(2*a1x - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta)) + (a1x - x - b1x*cos(theta) + b1y*sin(theta))^2 + (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2)^(1/2) + r_p*(pi - acos((y - a1y + b1y*cos(theta) + b1x*sin(theta))/((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2)^(1/2)) + acos((r_p*(2*a1x - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta)) + (a1x - x - b1x*cos(theta) + b1y*sin(theta))^2 + (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2)^(1/2)/((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2)^(1/2)) - 2237/12500))*(l1^2 - (12500*pi*r_p - 12500*r_p*acos((y - a1y + b1y*cos(theta) + b1x*sin(theta))/((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2)^(1/2)) - 2237*r_p + 12500*(r_p*(2*a1x - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta)) + (a1x - x - b1x*cos(theta) + b1y*sin(theta))^2 + (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2)^(1/2) + 12500*r_p*acos((r_p*(2*a1x - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta)) + (a1x - x - b1x*cos(theta) + b1y*sin(theta))^2 + (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2)^(1/2)/((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2)^(1/2)))^2/156250000)*(r_p*((a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2/(((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2)^(3/2)*(1 - (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2/((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2))^(1/2)) - (r_p^2*(y - a1y + b1y*cos(theta) + b1x*sin(theta)))/((1 - (r_p*(2*a1x - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta)) + (a1x - x - b1x*cos(theta) + b1y*sin(theta))^2 + (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2)/((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2))^(1/2)*((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2)^(3/2)*(r_p*(2*a1x - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta)) + (a1x - x - b1x*cos(theta) + b1y*sin(theta))^2 + (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2)^(1/2))) + (2*y - 2*a1y + 2*b1y*cos(theta) + 2*b1x*sin(theta))/(2*(r_p*(2*a1x - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta)) + (a1x - x - b1x*cos(theta) + b1y*sin(theta))^2 + (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2)^(1/2)));
    J1_theta = -4*((r_p*(2*a1x - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta)) + (a1x - x - b1x*cos(theta) + b1y*sin(theta))^2 + (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2)^(1/2) + r_p*(pi - acos((y - a1y + b1y*cos(theta) + b1x*sin(theta))/((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2)^(1/2)) + acos((r_p*(2*a1x - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta)) + (a1x - x - b1x*cos(theta) + b1y*sin(theta))^2 + (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2)^(1/2)/((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2)^(1/2)) - 2237/12500))*(l1^2 - (12500*pi*r_p - 12500*r_p*acos((y - a1y + b1y*cos(theta) + b1x*sin(theta))/((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2)^(1/2)) - 2237*r_p + 12500*(r_p*(2*a1x - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta)) + (a1x - x - b1x*cos(theta) + b1y*sin(theta))^2 + (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2)^(1/2) + 12500*r_p*acos((r_p*(2*a1x - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta)) + (a1x - x - b1x*cos(theta) + b1y*sin(theta))^2 + (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2)^(1/2)/((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2)^(1/2)))^2/156250000)*((2*a1x*b1x*sin(theta) + 2*a1y*b1y*sin(theta) + 2*b1y*r_p*cos(theta) - 2*b1y*x*cos(theta) + 2*b1x*y*cos(theta) + 2*b1x*r_p*sin(theta) - 2*b1x*x*sin(theta) - 2*b1y*y*sin(theta) + 2*a1x*b1y*cos(theta) - 2*a1y*b1x*cos(theta))/(2*(r_p*(2*a1x - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta)) + (a1x - x - b1x*cos(theta) + b1y*sin(theta))^2 + (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2)^(1/2)) - r_p*(((a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))*(b1x^2 + b1y^2 + a1x*b1y*sin(theta) - a1y*b1x*sin(theta) - b1x*r_p*cos(theta) + b1x*x*cos(theta) + b1y*y*cos(theta) + b1y*r_p*sin(theta) - b1y*x*sin(theta) + b1x*y*sin(theta) - a1x*b1x*cos(theta) - a1y*b1y*cos(theta)))/(((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2)^(3/2)*(1 - (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2/((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2))^(1/2)) + (r_p^2*(a1x*b1x*sin(theta) + a1y*b1y*sin(theta) + b1y*r_p*cos(theta) - b1y*x*cos(theta) + b1x*y*cos(theta) + b1x*r_p*sin(theta) - b1x*x*sin(theta) - b1y*y*sin(theta) + a1x*b1y*cos(theta) - a1y*b1x*cos(theta)))/((1 - (r_p*(2*a1x - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta)) + (a1x - x - b1x*cos(theta) + b1y*sin(theta))^2 + (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2)/((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2))^(1/2)*((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2)^(3/2)*(r_p*(2*a1x - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta)) + (a1x - x - b1x*cos(theta) + b1y*sin(theta))^2 + (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2)^(1/2))));
    
    J2_x = -4*((12500*(r_p*(2*a2x - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta)) + (a2x - x - b2x*cos(theta) + b2y*sin(theta))^2 + (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2)^(1/2) + r_p*(12500*acos((y - a2y + b2y*cos(theta) + b2x*sin(theta))/((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2)^(1/2)) + 12500*acos((r_p*(2*a2x - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta)) + (a2x - x - b2x*cos(theta) + b2y*sin(theta))^2 + (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2)^(1/2)/((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2)^(1/2)) - 2237))^2/156250000 - l2^2)*(r_p*(((y - a2y + b2y*cos(theta) + b2x*sin(theta))*(2*a2x + 2*r_p - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta)))/(2*((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2)^(3/2)*(1 - (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2/((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2))^(1/2)) - (r_p^2*(a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta)))/((1 - (r_p*(2*a2x - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta)) + (a2x - x - b2x*cos(theta) + b2y*sin(theta))^2 + (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2)/((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2))^(1/2)*((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2)^(3/2)*(r_p*(2*a2x - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta)) + (a2x - x - b2x*cos(theta) + b2y*sin(theta))^2 + (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2)^(1/2))) + (2*a2x + 2*r_p - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta))/(2*(r_p*(2*a2x - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta)) + (a2x - x - b2x*cos(theta) + b2y*sin(theta))^2 + (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2)^(1/2)))*(r_p*(acos((y - a2y + b2y*cos(theta) + b2x*sin(theta))/((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2)^(1/2)) + acos((r_p*(2*a2x - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta)) + (a2x - x - b2x*cos(theta) + b2y*sin(theta))^2 + (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2)^(1/2)/((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2)^(1/2)) - 2237/12500) + (r_p*(2*a2x - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta)) + (a2x - x - b2x*cos(theta) + b2y*sin(theta))^2 + (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2)^(1/2));
    J2_y = -4*((12500*(r_p*(2*a2x - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta)) + (a2x - x - b2x*cos(theta) + b2y*sin(theta))^2 + (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2)^(1/2) + r_p*(12500*acos((y - a2y + b2y*cos(theta) + b2x*sin(theta))/((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2)^(1/2)) + 12500*acos((r_p*(2*a2x - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta)) + (a2x - x - b2x*cos(theta) + b2y*sin(theta))^2 + (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2)^(1/2)/((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2)^(1/2)) - 2237))^2/156250000 - l2^2)*(r_p*((a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2/(((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2)^(3/2)*(1 - (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2/((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2))^(1/2)) + (r_p^2*(y - a2y + b2y*cos(theta) + b2x*sin(theta)))/((1 - (r_p*(2*a2x - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta)) + (a2x - x - b2x*cos(theta) + b2y*sin(theta))^2 + (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2)/((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2))^(1/2)*((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2)^(3/2)*(r_p*(2*a2x - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta)) + (a2x - x - b2x*cos(theta) + b2y*sin(theta))^2 + (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2)^(1/2))) - (2*y - 2*a2y + 2*b2y*cos(theta) + 2*b2x*sin(theta))/(2*(r_p*(2*a2x - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta)) + (a2x - x - b2x*cos(theta) + b2y*sin(theta))^2 + (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2)^(1/2)))*(r_p*(acos((y - a2y + b2y*cos(theta) + b2x*sin(theta))/((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2)^(1/2)) + acos((r_p*(2*a2x - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta)) + (a2x - x - b2x*cos(theta) + b2y*sin(theta))^2 + (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2)^(1/2)/((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2)^(1/2)) - 2237/12500) + (r_p*(2*a2x - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta)) + (a2x - x - b2x*cos(theta) + b2y*sin(theta))^2 + (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2)^(1/2));
    J2_theta = 4*((12500*(r_p*(2*a2x - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta)) + (a2x - x - b2x*cos(theta) + b2y*sin(theta))^2 + (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2)^(1/2) + r_p*(12500*acos((y - a2y + b2y*cos(theta) + b2x*sin(theta))/((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2)^(1/2)) + 12500*acos((r_p*(2*a2x - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta)) + (a2x - x - b2x*cos(theta) + b2y*sin(theta))^2 + (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2)^(1/2)/((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2)^(1/2)) - 2237))^2/156250000 - l2^2)*((2*a2x*b2x*sin(theta) + 2*a2y*b2y*sin(theta) + 2*b2y*r_p*cos(theta) - 2*b2y*x*cos(theta) + 2*b2x*y*cos(theta) + 2*b2x*r_p*sin(theta) - 2*b2x*x*sin(theta) - 2*b2y*y*sin(theta) + 2*a2x*b2y*cos(theta) - 2*a2y*b2x*cos(theta))/(2*(r_p*(2*a2x - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta)) + (a2x - x - b2x*cos(theta) + b2y*sin(theta))^2 + (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2)^(1/2)) + r_p*(((a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))*(b2x^2 + b2y^2 + a2x*b2y*sin(theta) - a2y*b2x*sin(theta) - b2x*r_p*cos(theta) + b2x*x*cos(theta) + b2y*y*cos(theta) + b2y*r_p*sin(theta) - b2y*x*sin(theta) + b2x*y*sin(theta) - a2x*b2x*cos(theta) - a2y*b2y*cos(theta)))/(((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2)^(3/2)*(1 - (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2/((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2))^(1/2)) - (r_p^2*(a2x*b2x*sin(theta) + a2y*b2y*sin(theta) + b2y*r_p*cos(theta) - b2y*x*cos(theta) + b2x*y*cos(theta) + b2x*r_p*sin(theta) - b2x*x*sin(theta) - b2y*y*sin(theta) + a2x*b2y*cos(theta) - a2y*b2x*cos(theta)))/((1 - (r_p*(2*a2x - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta)) + (a2x - x - b2x*cos(theta) + b2y*sin(theta))^2 + (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2)/((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2))^(1/2)*((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2)^(3/2)*(r_p*(2*a2x - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta)) + (a2x - x - b2x*cos(theta) + b2y*sin(theta))^2 + (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2)^(1/2))))*(r_p*(acos((y - a2y + b2y*cos(theta) + b2x*sin(theta))/((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2)^(1/2)) + acos((r_p*(2*a2x - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta)) + (a2x - x - b2x*cos(theta) + b2y*sin(theta))^2 + (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2)^(1/2)/((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2)^(1/2)) - 2237/12500) + (r_p*(2*a2x - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta)) + (a2x - x - b2x*cos(theta) + b2y*sin(theta))^2 + (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2)^(1/2));
    
    J3_x = 4*((12500*((a3x - x - b3x*cos(theta) + b3y*sin(theta))^2 - r_p*(2*a3x - 2*x - 2*b3x*cos(theta) + 2*b3y*sin(theta)) + (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2)^(1/2) + r_p*(12500*acos((y - a3y + b3y*cos(theta) + b3x*sin(theta))/((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2)^(1/2)) + 12500*acos(((a3x - x - b3x*cos(theta) + b3y*sin(theta))^2 - r_p*(2*a3x - 2*x - 2*b3x*cos(theta) + 2*b3y*sin(theta)) + (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2)^(1/2)/((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2)^(1/2)) - 2237))^2/156250000 - l3^2)*(r_p*(((y - a3y + b3y*cos(theta) + b3x*sin(theta))*(2*r_p - 2*a3x + 2*x + 2*b3x*cos(theta) - 2*b3y*sin(theta)))/(2*((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2)^(3/2)*(1 - (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2/((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2))^(1/2)) - (r_p^2*(r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta)))/((1 - ((a3x - x - b3x*cos(theta) + b3y*sin(theta))^2 - r_p*(2*a3x - 2*x - 2*b3x*cos(theta) + 2*b3y*sin(theta)) + (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2)/((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2))^(1/2)*((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2)^(3/2)*((a3x - x - b3x*cos(theta) + b3y*sin(theta))^2 - r_p*(2*a3x - 2*x - 2*b3x*cos(theta) + 2*b3y*sin(theta)) + (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2)^(1/2))) + (2*r_p - 2*a3x + 2*x + 2*b3x*cos(theta) - 2*b3y*sin(theta))/(2*((a3x - x - b3x*cos(theta) + b3y*sin(theta))^2 - r_p*(2*a3x - 2*x - 2*b3x*cos(theta) + 2*b3y*sin(theta)) + (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2)^(1/2)))*(r_p*(acos((y - a3y + b3y*cos(theta) + b3x*sin(theta))/((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2)^(1/2)) + acos(((a3x - x - b3x*cos(theta) + b3y*sin(theta))^2 - r_p*(2*a3x - 2*x - 2*b3x*cos(theta) + 2*b3y*sin(theta)) + (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2)^(1/2)/((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2)^(1/2)) - 2237/12500) + ((a3x - x - b3x*cos(theta) + b3y*sin(theta))^2 - r_p*(2*a3x - 2*x - 2*b3x*cos(theta) + 2*b3y*sin(theta)) + (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2)^(1/2));
    J3_y = -4*((12500*((a3x - x - b3x*cos(theta) + b3y*sin(theta))^2 - r_p*(2*a3x - 2*x - 2*b3x*cos(theta) + 2*b3y*sin(theta)) + (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2)^(1/2) + r_p*(12500*acos((y - a3y + b3y*cos(theta) + b3x*sin(theta))/((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2)^(1/2)) + 12500*acos(((a3x - x - b3x*cos(theta) + b3y*sin(theta))^2 - r_p*(2*a3x - 2*x - 2*b3x*cos(theta) + 2*b3y*sin(theta)) + (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2)^(1/2)/((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2)^(1/2)) - 2237))^2/156250000 - l3^2)*(r_p*((r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2/(((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2)^(3/2)*(1 - (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2/((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2))^(1/2)) + (r_p^2*(y - a3y + b3y*cos(theta) + b3x*sin(theta)))/((1 - ((a3x - x - b3x*cos(theta) + b3y*sin(theta))^2 - r_p*(2*a3x - 2*x - 2*b3x*cos(theta) + 2*b3y*sin(theta)) + (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2)/((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2))^(1/2)*((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2)^(3/2)*((a3x - x - b3x*cos(theta) + b3y*sin(theta))^2 - r_p*(2*a3x - 2*x - 2*b3x*cos(theta) + 2*b3y*sin(theta)) + (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2)^(1/2))) - (2*y - 2*a3y + 2*b3y*cos(theta) + 2*b3x*sin(theta))/(2*((a3x - x - b3x*cos(theta) + b3y*sin(theta))^2 - r_p*(2*a3x - 2*x - 2*b3x*cos(theta) + 2*b3y*sin(theta)) + (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2)^(1/2)))*(r_p*(acos((y - a3y + b3y*cos(theta) + b3x*sin(theta))/((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2)^(1/2)) + acos(((a3x - x - b3x*cos(theta) + b3y*sin(theta))^2 - r_p*(2*a3x - 2*x - 2*b3x*cos(theta) + 2*b3y*sin(theta)) + (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2)^(1/2)/((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2)^(1/2)) - 2237/12500) + ((a3x - x - b3x*cos(theta) + b3y*sin(theta))^2 - r_p*(2*a3x - 2*x - 2*b3x*cos(theta) + 2*b3y*sin(theta)) + (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2)^(1/2));
    J3_theta = -4*((12500*((a3x - x - b3x*cos(theta) + b3y*sin(theta))^2 - r_p*(2*a3x - 2*x - 2*b3x*cos(theta) + 2*b3y*sin(theta)) + (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2)^(1/2) + r_p*(12500*acos((y - a3y + b3y*cos(theta) + b3x*sin(theta))/((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2)^(1/2)) + 12500*acos(((a3x - x - b3x*cos(theta) + b3y*sin(theta))^2 - r_p*(2*a3x - 2*x - 2*b3x*cos(theta) + 2*b3y*sin(theta)) + (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2)^(1/2)/((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2)^(1/2)) - 2237))^2/156250000 - l3^2)*((2*b3y*r_p*cos(theta) - 2*a3y*b3y*sin(theta) - 2*a3x*b3x*sin(theta) + 2*b3y*x*cos(theta) - 2*b3x*y*cos(theta) + 2*b3x*r_p*sin(theta) + 2*b3x*x*sin(theta) + 2*b3y*y*sin(theta) - 2*a3x*b3y*cos(theta) + 2*a3y*b3x*cos(theta))/(2*((a3x - x - b3x*cos(theta) + b3y*sin(theta))^2 - r_p*(2*a3x - 2*x - 2*b3x*cos(theta) + 2*b3y*sin(theta)) + (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2)^(1/2)) + r_p*(((r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))*(b3x^2 + b3y^2 + a3x*b3y*sin(theta) - a3y*b3x*sin(theta) + b3x*r_p*cos(theta) + b3x*x*cos(theta) + b3y*y*cos(theta) - b3y*r_p*sin(theta) - b3y*x*sin(theta) + b3x*y*sin(theta) - a3x*b3x*cos(theta) - a3y*b3y*cos(theta)))/(((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2)^(3/2)*(1 - (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2/((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2))^(1/2)) - (r_p^2*(b3y*r_p*cos(theta) - a3y*b3y*sin(theta) - a3x*b3x*sin(theta) + b3y*x*cos(theta) - b3x*y*cos(theta) + b3x*r_p*sin(theta) + b3x*x*sin(theta) + b3y*y*sin(theta) - a3x*b3y*cos(theta) + a3y*b3x*cos(theta)))/((1 - ((a3x - x - b3x*cos(theta) + b3y*sin(theta))^2 - r_p*(2*a3x - 2*x - 2*b3x*cos(theta) + 2*b3y*sin(theta)) + (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2)/((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2))^(1/2)*((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2)^(3/2)*((a3x - x - b3x*cos(theta) + b3y*sin(theta))^2 - r_p*(2*a3x - 2*x - 2*b3x*cos(theta) + 2*b3y*sin(theta)) + (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2)^(1/2))))*(r_p*(acos((y - a3y + b3y*cos(theta) + b3x*sin(theta))/((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2)^(1/2)) + acos(((a3x - x - b3x*cos(theta) + b3y*sin(theta))^2 - r_p*(2*a3x - 2*x - 2*b3x*cos(theta) + 2*b3y*sin(theta)) + (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2)^(1/2)/((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2)^(1/2)) - 2237/12500) + ((a3x - x - b3x*cos(theta) + b3y*sin(theta))^2 - r_p*(2*a3x - 2*x - 2*b3x*cos(theta) + 2*b3y*sin(theta)) + (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2)^(1/2));
    
    J4_x = 4*(r_p*(((y - a4y + b4y*cos(theta) + b4x*sin(theta))*(2*r_p - 2*a4x + 2*x + 2*b4x*cos(theta) - 2*b4y*sin(theta)))/(2*((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2)^(3/2)*(1 - (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2/((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2))^(1/2)) + (r_p^2*(r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta)))/((1 - ((a4x - x - b4x*cos(theta) + b4y*sin(theta))^2 - r_p*(2*a4x - 2*x - 2*b4x*cos(theta) + 2*b4y*sin(theta)) + (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2)/((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2))^(1/2)*((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2)^(3/2)*((a4x - x - b4x*cos(theta) + b4y*sin(theta))^2 - r_p*(2*a4x - 2*x - 2*b4x*cos(theta) + 2*b4y*sin(theta)) + (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2)^(1/2))) - (2*r_p - 2*a4x + 2*x + 2*b4x*cos(theta) - 2*b4y*sin(theta))/(2*((a4x - x - b4x*cos(theta) + b4y*sin(theta))^2 - r_p*(2*a4x - 2*x - 2*b4x*cos(theta) + 2*b4y*sin(theta)) + (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2)^(1/2)))*(((a4x - x - b4x*cos(theta) + b4y*sin(theta))^2 - r_p*(2*a4x - 2*x - 2*b4x*cos(theta) + 2*b4y*sin(theta)) + (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2)^(1/2) + r_p*(pi - acos((y - a4y + b4y*cos(theta) + b4x*sin(theta))/((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2)^(1/2)) + acos(((a4x - x - b4x*cos(theta) + b4y*sin(theta))^2 - r_p*(2*a4x - 2*x - 2*b4x*cos(theta) + 2*b4y*sin(theta)) + (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2)^(1/2)/((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2)^(1/2)) - 2237/12500))*(l4^2 - (12500*pi*r_p - 12500*r_p*acos((y - a4y + b4y*cos(theta) + b4x*sin(theta))/((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2)^(1/2)) - 2237*r_p + 12500*((a4x - x - b4x*cos(theta) + b4y*sin(theta))^2 - r_p*(2*a4x - 2*x - 2*b4x*cos(theta) + 2*b4y*sin(theta)) + (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2)^(1/2) + 12500*r_p*acos(((a4x - x - b4x*cos(theta) + b4y*sin(theta))^2 - r_p*(2*a4x - 2*x - 2*b4x*cos(theta) + 2*b4y*sin(theta)) + (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2)^(1/2)/((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2)^(1/2)))^2/156250000);
    J4_y = -4*(((a4x - x - b4x*cos(theta) + b4y*sin(theta))^2 - r_p*(2*a4x - 2*x - 2*b4x*cos(theta) + 2*b4y*sin(theta)) + (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2)^(1/2) + r_p*(pi - acos((y - a4y + b4y*cos(theta) + b4x*sin(theta))/((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2)^(1/2)) + acos(((a4x - x - b4x*cos(theta) + b4y*sin(theta))^2 - r_p*(2*a4x - 2*x - 2*b4x*cos(theta) + 2*b4y*sin(theta)) + (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2)^(1/2)/((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2)^(1/2)) - 2237/12500))*(l4^2 - (12500*pi*r_p - 12500*r_p*acos((y - a4y + b4y*cos(theta) + b4x*sin(theta))/((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2)^(1/2)) - 2237*r_p + 12500*((a4x - x - b4x*cos(theta) + b4y*sin(theta))^2 - r_p*(2*a4x - 2*x - 2*b4x*cos(theta) + 2*b4y*sin(theta)) + (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2)^(1/2) + 12500*r_p*acos(((a4x - x - b4x*cos(theta) + b4y*sin(theta))^2 - r_p*(2*a4x - 2*x - 2*b4x*cos(theta) + 2*b4y*sin(theta)) + (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2)^(1/2)/((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2)^(1/2)))^2/156250000)*(r_p*((r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2/(((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2)^(3/2)*(1 - (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2/((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2))^(1/2)) - (r_p^2*(y - a4y + b4y*cos(theta) + b4x*sin(theta)))/((1 - ((a4x - x - b4x*cos(theta) + b4y*sin(theta))^2 - r_p*(2*a4x - 2*x - 2*b4x*cos(theta) + 2*b4y*sin(theta)) + (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2)/((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2))^(1/2)*((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2)^(3/2)*((a4x - x - b4x*cos(theta) + b4y*sin(theta))^2 - r_p*(2*a4x - 2*x - 2*b4x*cos(theta) + 2*b4y*sin(theta)) + (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2)^(1/2))) + (2*y - 2*a4y + 2*b4y*cos(theta) + 2*b4x*sin(theta))/(2*((a4x - x - b4x*cos(theta) + b4y*sin(theta))^2 - r_p*(2*a4x - 2*x - 2*b4x*cos(theta) + 2*b4y*sin(theta)) + (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2)^(1/2)));
    J4_theta = 4*(((a4x - x - b4x*cos(theta) + b4y*sin(theta))^2 - r_p*(2*a4x - 2*x - 2*b4x*cos(theta) + 2*b4y*sin(theta)) + (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2)^(1/2) + r_p*(pi - acos((y - a4y + b4y*cos(theta) + b4x*sin(theta))/((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2)^(1/2)) + acos(((a4x - x - b4x*cos(theta) + b4y*sin(theta))^2 - r_p*(2*a4x - 2*x - 2*b4x*cos(theta) + 2*b4y*sin(theta)) + (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2)^(1/2)/((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2)^(1/2)) - 2237/12500))*(l4^2 - (12500*pi*r_p - 12500*r_p*acos((y - a4y + b4y*cos(theta) + b4x*sin(theta))/((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2)^(1/2)) - 2237*r_p + 12500*((a4x - x - b4x*cos(theta) + b4y*sin(theta))^2 - r_p*(2*a4x - 2*x - 2*b4x*cos(theta) + 2*b4y*sin(theta)) + (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2)^(1/2) + 12500*r_p*acos(((a4x - x - b4x*cos(theta) + b4y*sin(theta))^2 - r_p*(2*a4x - 2*x - 2*b4x*cos(theta) + 2*b4y*sin(theta)) + (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2)^(1/2)/((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2)^(1/2)))^2/156250000)*((2*b4y*r_p*cos(theta) - 2*a4y*b4y*sin(theta) - 2*a4x*b4x*sin(theta) + 2*b4y*x*cos(theta) - 2*b4x*y*cos(theta) + 2*b4x*r_p*sin(theta) + 2*b4x*x*sin(theta) + 2*b4y*y*sin(theta) - 2*a4x*b4y*cos(theta) + 2*a4y*b4x*cos(theta))/(2*((a4x - x - b4x*cos(theta) + b4y*sin(theta))^2 - r_p*(2*a4x - 2*x - 2*b4x*cos(theta) + 2*b4y*sin(theta)) + (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2)^(1/2)) - r_p*(((r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))*(b4x^2 + b4y^2 + a4x*b4y*sin(theta) - a4y*b4x*sin(theta) + b4x*r_p*cos(theta) + b4x*x*cos(theta) + b4y*y*cos(theta) - b4y*r_p*sin(theta) - b4y*x*sin(theta) + b4x*y*sin(theta) - a4x*b4x*cos(theta) - a4y*b4y*cos(theta)))/(((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2)^(3/2)*(1 - (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2/((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2))^(1/2)) + (r_p^2*(b4y*r_p*cos(theta) - a4y*b4y*sin(theta) - a4x*b4x*sin(theta) + b4y*x*cos(theta) - b4x*y*cos(theta) + b4x*r_p*sin(theta) + b4x*x*sin(theta) + b4y*y*sin(theta) - a4x*b4y*cos(theta) + a4y*b4x*cos(theta)))/((1 - ((a4x - x - b4x*cos(theta) + b4y*sin(theta))^2 - r_p*(2*a4x - 2*x - 2*b4x*cos(theta) + 2*b4y*sin(theta)) + (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2)/((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2))^(1/2)*((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2)^(3/2)*((a4x - x - b4x*cos(theta) + b4y*sin(theta))^2 - r_p*(2*a4x - 2*x - 2*b4x*cos(theta) + 2*b4y*sin(theta)) + (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2)^(1/2))));


    J = [J1_x J1_y J1_theta;
         J2_x J2_y J2_theta;
         J3_x J3_y J3_theta;
         J4_x J4_y J4_theta];

end

function nusqv = nusq(a, b, pose, l, r_p)
    x = pose(1);
    y = pose(2);
    theta = pose(3);
    
    c = cos(theta);
    s = sin(theta);

    a1x = a(1,1);
    a1y = a(2,1);
    a2x = a(1,2);
    a2y = a(2,2);
    a3x = a(1,3);
    a3y = a(2,3);
    a4x = a(1,4);
    a4y = a(2,4);

    b1x = b(1,1);
    b1y = b(2,1);
    b2x = b(1,2);
    b2y = b(2,2);
    b3x = b(1,3);
    b3y = b(2,3);
    b4x = b(1,4);
    b4y = b(2,4);

    l1 = l(1);
    l2 = l(2);
    l3 = l(3);
    l4 = l(4);

%     nu1sq = (                                           ...
%                 r_p*(2*a1x - 2*x - 2*b1x*c + 2*b1y*s) + ...
%                 (a1x - x - b1x*c + b1y*s)^2 +           ...
%                 (y - a1y + b1y*c + b1x*s)^2 -           ...
%                 l1^2                                    ...
%             )^2;
%     nu2sq = (                                           ...
%                 r_p*(2*a2x - 2*x - 2*b2x*c + 2*b2y*s) + ...
%                 (a2x - x - b2x*c + b2y*s)^2 +           ...
%                 (y - a2y + b2y*c + b2x*s)^2 -           ...
%                 l2^2                                    ...
%             )^2; 
%     nu3sq = (                                           ...
%                 r_p*(2*a3x - 2*x - 2*b3x*c + 2*b3y*s) - ...
%                 (a3x - x - b3x*c + b3y*s)^2 -           ...
%                 (y - a3y + b3y*c + b3x*s)^2 +           ...
%                 l3^2                                    ...
%             )^2;
%     nu4sq = (                                           ...
%                 r_p*(2*a4x - 2*x - 2*b4x*c + 2*b4y*s) - ...
%                 (a4x - x - b4x*c + b4y*s)^2 -           ...
%                 (y - a4y + b4y*c + b4x*s)^2 +           ...
%                 l4^2                                    ...
%             )^2;
    nu1sq = (((r_p*(2*a1x - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta)) + (a1x - x - b1x*cos(theta) + b1y*sin(theta))^2 + (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2)^(1/2) + r_p*(pi - acos((y - a1y + b1y*cos(theta) + b1x*sin(theta))/((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2)^(1/2)) + acos((r_p*(2*a1x - 2*x - 2*b1x*cos(theta) + 2*b1y*sin(theta)) + (a1x - x - b1x*cos(theta) + b1y*sin(theta))^2 + (y - a1y + b1y*cos(theta) + b1x*sin(theta))^2)^(1/2)/((y - a1y + b1y*cos(theta) + b1x*sin(theta))^2 + (a1x + r_p - x - b1x*cos(theta) + b1y*sin(theta))^2)^(1/2)) - 2237/12500))^2 - l1^2)^2;
    nu2sq = ((r_p*(acos((y - a2y + b2y*cos(theta) + b2x*sin(theta))/((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2)^(1/2)) + acos((r_p*(2*a2x - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta)) + (a2x - x - b2x*cos(theta) + b2y*sin(theta))^2 + (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2)^(1/2)/((y - a2y + b2y*cos(theta) + b2x*sin(theta))^2 + (a2x + r_p - x - b2x*cos(theta) + b2y*sin(theta))^2)^(1/2)) - 2237/12500) + (r_p*(2*a2x - 2*x - 2*b2x*cos(theta) + 2*b2y*sin(theta)) + (a2x - x - b2x*cos(theta) + b2y*sin(theta))^2 + (y - a2y + b2y*cos(theta) + b2x*sin(theta))^2)^(1/2))^2 - l2^2)^2;
    nu3sq = ((r_p*(acos((y - a3y + b3y*cos(theta) + b3x*sin(theta))/((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2)^(1/2)) + acos(((a3x - x - b3x*cos(theta) + b3y*sin(theta))^2 - r_p*(2*a3x - 2*x - 2*b3x*cos(theta) + 2*b3y*sin(theta)) + (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2)^(1/2)/((y - a3y + b3y*cos(theta) + b3x*sin(theta))^2 + (r_p - a3x + x + b3x*cos(theta) - b3y*sin(theta))^2)^(1/2)) - 2237/12500) + ((a3x - x - b3x*cos(theta) + b3y*sin(theta))^2 - r_p*(2*a3x - 2*x - 2*b3x*cos(theta) + 2*b3y*sin(theta)) + (y - a3y + b3y*cos(theta) + b3x*sin(theta))^2)^(1/2))^2 - l3^2)^2;
    nu4sq = ((((a4x - x - b4x*cos(theta) + b4y*sin(theta))^2 - r_p*(2*a4x - 2*x - 2*b4x*cos(theta) + 2*b4y*sin(theta)) + (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2)^(1/2) + r_p*(pi - acos((y - a4y + b4y*cos(theta) + b4x*sin(theta))/((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2)^(1/2)) + acos(((a4x - x - b4x*cos(theta) + b4y*sin(theta))^2 - r_p*(2*a4x - 2*x - 2*b4x*cos(theta) + 2*b4y*sin(theta)) + (y - a4y + b4y*cos(theta) + b4x*sin(theta))^2)^(1/2)/((y - a4y + b4y*cos(theta) + b4x*sin(theta))^2 + (r_p - a4x + x + b4x*cos(theta) - b4y*sin(theta))^2)^(1/2)) - 2237/12500))^2 - l4^2)^2;

    nusqv = [nu1sq; nu2sq; nu3sq; nu4sq];

end