function Gradient_x = GradientObj(in1,f_min,f_max,f_ref,p,c,b,epsilon)
%GradientObj
%    Gradient_x = GradientObj(IN1,F_MIN,F_MAX,F_REF,P,C,B,EPSILON)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    15-Apr-2024 20:14:29

f1 = in1(1,:);
f2 = in1(2,:);
f3 = in1(3,:);
f4 = in1(4,:);
s1 = in1(5,:);
s2 = in1(6,:);
s3 = in1(7,:);
t2 = -f_min;
t3 = -f_max;
t4 = -f_ref;
t5 = -p;
t6 = p-1.0;
t7 = f_min./2.0;
t8 = f_max./2.0;
t9 = -t7;
t10 = t8+t9;
t11 = t10.^t5;
Gradient_x = [-c./(f1+t2)-c./(f1+t3)+p.*t11.*(f1+t4).^t6,-c./(f2+t2)-c./(f2+t3)+p.*t11.*(f2+t4).^t6,-c./(f3+t2)-c./(f3+t3)+p.*t11.*(f3+t4).^t6,-c./(f4+t2)-c./(f4+t3)+p.*t11.*(f4+t4).^t6,s1.*2.0+b.*s1.*1.0./sqrt(epsilon+s1.^2),s2.*2.0+b.*s2.*1.0./sqrt(epsilon+s2.^2),s3.*2.0+b.*s3.*1.0./sqrt(epsilon+s3.^2)];
end
