function g_x = ObjectiveFun(in1,f_min,f_max,f_ref,p,c,b,epsilon)
%ObjectiveFun
%    G_X = ObjectiveFun(IN1,F_MIN,F_MAX,F_REF,P,C,B,EPSILON)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    15-Apr-2024 20:14:28

f1 = in1(1,:);
f2 = in1(2,:);
f3 = in1(3,:);
f4 = in1(4,:);
s1 = in1(5,:);
s2 = in1(6,:);
s3 = in1(7,:);
t2 = s1.^2;
t3 = s2.^2;
t4 = s3.^2;
t5 = -f_min;
t6 = -f_ref;
t7 = -p;
t8 = f_min./2.0;
t9 = f_max./2.0;
t10 = -t8;
t11 = t9+t10;
t12 = t11.^t7;
g_x = t2+t3+t4+b.*sqrt(epsilon+t2)+b.*sqrt(epsilon+t3)+b.*sqrt(epsilon+t4)-c.*log(f1+t5)-c.*log(f2+t5)-c.*log(f3+t5)-c.*log(f4+t5)-c.*log(-f1+f_max)-c.*log(-f2+f_max)-c.*log(-f3+f_max)-c.*log(-f4+f_max)+t12.*(f1+t6).^p+t12.*(f2+t6).^p+t12.*(f3+t6).^p+t12.*(f4+t6).^p;
end
